import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const theSeasons = localFont({
  src: [
    { path: "../../public/fonts/TheSeasons-Light.woff2", weight: "300" },
    { path: "../../public/fonts/TheSeasons-Regular.woff2", weight: "400" },
    { path: "../../public/fonts/TheSeasons-Bold.woff2", weight: "700" },
  ],
  variable: "--font-the-seasons",
  display: "swap",
});

export const metadata = {
  title: "Secure Clinics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${theSeasons.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
