import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const theSeasons = localFont({
  src: [
    {
      path: "./fonts/TheSeasons-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/TheSeasons-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/TheSeasons-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/theseasons-it.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/theseasons-bdit.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-the-seasons",
  display: "swap",
});

export const metadata = {
  title: "Secure Clinics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className={`${theSeasons.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}